# Generated by Django 2.1.5 on 2019-02-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasemodel',
            old_name='testcase_configFile',
            new_name='testcase_type',
        ),
    ]
