# Generated by Django 2.1.5 on 2019-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testcaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_simulation', models.BooleanField()),
                ('testcase_channel', models.IntegerField()),
                ('testcase_configFile', models.TextField(null=True)),
                ('testcase_nameCarac', models.TextField(null=True)),
                ('testcase_climChamber', models.BooleanField()),
            ],
        ),
    ]
