# Generated by Django 2.2.2 on 2019-07-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressCalib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
