# Generated by Django 2.2.2 on 2019-07-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagnmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campagn_channels', models.CharField(max_length=100)),
                ('campagn_type', models.CharField(max_length=200)),
                ('campagn_name', models.CharField(max_length=200)),
                ('campagn_climChamber', models.CharField(max_length=50)),
                ('campagn_date', models.CharField(max_length=200)),
                ('campagn_clim_total', models.IntegerField()),
                ('campagm_clim_current', models.IntegerField()),
                ('campagn_tc2play', models.CharField(max_length=400)),
                ('campagn_templist', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Progressbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField()),
                ('total', models.IntegerField()),
                ('tc_current', models.IntegerField()),
                ('tc_total', models.IntegerField()),
                ('tc', models.CharField(max_length=100)),
                ('responseTask', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testcasemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_simulation', models.BooleanField()),
                ('testcase_channels', models.IntegerField()),
                ('testcase_type', models.TextField(null=True)),
                ('testcase_nameCarac', models.TextField(null=True)),
                ('testcase_climChamber', models.BooleanField()),
            ],
        ),
    ]
